version: '3'
services:
  db:
    image: postgres:14
    container_name: postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=card_transaction
    volumes:
      - ~/Documents/volumes/postgresql:/var/lib/postgresql/data
    restart: always

  card-transaction-app:
    build:
      dockerfile: Dockerfile
    container_name: card_transaction_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/card_transaction
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    restart: always