package com.test.service.exceptions;

public enum ErrorCodes {
    INVALID_INPUT_REQUEST,
    ACCOUNT_ALREADY_EXIST,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_BALANCE_INSUFFICIENT,
    OPERATION_TYPE_ALREADY_EXIST,
    OPERATION_TYPE_NOT_FOUND
}
